version: "2"

services:
  mongo1:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27018:27017"
    environment:
    - MONGO_ROLE=primary
    - AUTH=yes
    - REP_SET=rs0
    - MONGO_CONF_REPSET={_id:'rs0',members:[{_id:1,host:'mongo1'},{_id:2,host:'mongo2'},{_id:3,host:'mongo3'}]}
    - MONGO_ROOT_USER=root
    - MONGO_ROOT_PASSWORD=root123
    - KEY_REP_SET=tototata
    networks:
    - my-mongo-net
    container_name: mongo1
  mongo2:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27019:27017"
    environment:
    - AUTH=yes
    - REP_SET=rs0
    - VERBOSE=yes
    - KEY_REP_SET=tototata
    networks:
    - my-mongo-net
    container_name: mongo2
  mongo3:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27020:27017"
    environment:
    - AUTH=yes
    - REP_SET=rs0
    - KEY_REP_SET=tototata
    networks:
    - my-mongo-net
    container_name: mongo3

networks:
  my-mongo-net:
    driver: bridge