version: "2"

services:
  mongo1:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27017:27017"
    environment:
    - MONGO_ROLE=primary
    - REP_SET=rs0
    - MONGO_CONF_REPSET={_id:'rs0',members:[{_id:1,host:'mongo1'},{_id:2,host:'mongo2'},{_id:3,host:'mongo3'}]}
    - MONGO_ROOT_USER=root
    - MONGO_ROOT_PASSWORD=root123
    - KEY_REP_SET=tototata
#    - NO_AUTH=true
    container_name: mongo1
  mongo2:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27018:27017"
    environment:
    - REP_SET=rs0
    - VERBOSE=no
    - KEY_REP_SET=tototata
#    - NO_AUTH=true
    container_name: mongo2
  mongo3:
    image: bappr/mongo-rep-set:latest
    ports:
    - "27019:27017"
    environment:
    - REP_SET=rs0
    - KEY_REP_SET=tototata
#    - NO_AUTH=true
    container_name: mongo3
